rvm:
  - 2.0
  - 2.1
  - 2.2.3
bundler_args: ""
branches:
  only:
    - master
    - stable
    - rails4.x
    
env: RAILS_ENV=test
services: mongodb
script: "bundle exec rake secret:replace && bundle exec rake"
